# Generated by Django 2.1 on 2018-08-18 03:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20180817_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, verbose_name='Phone (eg +919898989899)'),
        ),
        migrations.AlterField(
            model_name='districtmanager',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, verbose_name='Phone (eg +919898989899)'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, verbose_name='Phone (eg +919898989899)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile - മൊബൈൽ'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Requestee Phone - അപേക്ഷകന്\u200dറെ ഫോണ്\u200d നമ്പര്\u200d'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, verbose_name='Phone (eg +919898989899)'),
        ),
    ]
